- name: update dns record
  command: /opt/venv/haproxy/bin/python3 "roles/{{ role_name }}/files/update_dns.py"
  register: update_dns_record

- name: print dns update result
  debug:
    msg: "{{ update_dns_record.stdout_lines }}"