- name: yum install packages
  yum:
    name: ['epel-release', 'etckeeper', 'haproxy', 'fail2ban', 'python3', 'python3-pip', 'tmux', 'chrony', 'vim-enhanced']
    state: latest
  notify:
    - restart haproxy
    - restart fail2ban
    - stop firewalld
    - restart chronyd
