- name: restart haproxy
  service: name=haproxy state=restarted enabled=yes
- name: stop firewalld
  service: name=firewalld state=stopped enabled=no 
- name: restart fail2ban
  service: name=fail2ban state=restarted enabled=yes
- name: restart chronyd
  service: name=chronyd state=restarted enabled=yes